services:
  postgres:
    image: postgres:17.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api:
  #   image: zero2prod:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     APP_APPLICATION__PORT: 8000
  #     APP_APPLICATION_HOST: "0.0.0.0"
  #     APP_DATABASE__HOST: "postgres"
  #     APP_DATABASE__USERNAME: "postgres"
  #     APP_DATABASE__PASSWORDD: "password"
  #     APP_DATABASE__DATABASE_NAME: "newsletter"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true

volumes:
  postgres-data: