apiVersion: v1
kind: Service
metadata:
  name: zero2prod-api-svc
  namespace: zero2prod
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: zero2prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2prod-api
  namespace: zero2prod
spec:
  selector:
    matchLabels:
      app: zero2prod
  replicas: 1
  template:
    metadata:
      labels:
        app: zero2prod
    spec:
      containers:
      - name: zero2prod
        image: ghcr.io/marcobacis/zero2prod:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: 
        env:
        - name: APP_APPLICATION__PORT
          value: "80"
        - name: APP_APPLICATION__HOST
          value: "0.0.0.0"
        - name: APP_APPLICATION__BASE_URL
          value: "https://zerotoprod.marcobacis.com"
        - name: APP_APPLICATION__HMAC_SECRET
          valueFrom:
            secretKeyRef:
              name: zero2prod-config
              key: hmac-secret
        - name: APP_DATABASE__HOST
          value: "zero2prod-db-svc.zero2prod.svc.cluster.local"
        - name: APP_DATABASE__USERNAME
          valueFrom:
            secretKeyRef:
              name: zero2prod-config
              key: pg-username
        - name: APP_DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: zero2prod-config
              key: pg-password
        - name: APP_DATABASE__DATABASE_NAME
          value: "newsletter"
        - name: APP_REDIS_URI
          value: "redis://redis.zero2prod.svc.cluster.local:6379"
        - name: APP_EMAIL_CLIENT__TOKEN
          valueFrom:
            secretKeyRef:
              name: zero2prod-config
              key: postmark-token