apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zero2prod-ingress
  namespace: zero2prod
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: zerotoprod.marcobacis.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: zero2prod-api-svc
                port:
                  number: 80